<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_1698761799412</name>
   <tag></tag>
   <elementGuidId>c602bd20-f561-449c-b541-e81d116c3cdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>b16b37a0-28c9-44d7-acaa-6765dcc32710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1698761799412</value>
      <webElementGuid>1acb9158-c1d8-4ca7-a0d5-ffba6e633ef0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
