<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>21943f36-6f8e-4b40-830e-f29588a7a01d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;IMG-PRODUCT&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='IMG-PRODUCT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5b2427f2-7786-466b-af95-cef5662cee1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-max-den-thumb-600x600.jpg</value>
      <webElementGuid>81986141-d92d-4648-ad72-d0f1681019eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>IMG-PRODUCT</value>
      <webElementGuid>61b5a13e-0720-41fc-b9d8-fac9f0aedc4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;animsition&quot;]/section[@class=&quot;bg0 p-t-23 p-b-50&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row isotope-grid&quot;]/div[@class=&quot;col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item women&quot;]/div[@class=&quot;block2&quot;]/div[@class=&quot;block2-pic hov-img0&quot;]/img[1]</value>
      <webElementGuid>e89486ed-ec9b-4993-bddb-cc5d2ac164fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='IMG-PRODUCT']</value>
      <webElementGuid>faba323d-d7cf-4f8c-85da-659a587d8eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>3f2bf85f-7388-4670-aedc-1e3c83f58616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-max-den-thumb-600x600.jpg' and @alt = 'IMG-PRODUCT']</value>
      <webElementGuid>852999fd-56b0-4811-acf9-80d565ef9493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
