<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping_address</name>
   <tag></tag>
   <elementGuidId>840fe8d7-1404-4ce8-9a05-e574e44f3a0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;address&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;animsition&quot;]/form[@class=&quot;bg0 p-t-75 p-b-85&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50&quot;]/div[@class=&quot;bor10 p-lr-40 p-t-30 p-b-40 m-l-63  m-lr-0-xl p-lr-15-sm&quot;]/div[@class=&quot;flex-w flex-t bor12 p-t-15 p-b-30&quot;]/div[@class=&quot;size-209 p-r-18 p-r-0-sm w-full-ssm&quot;]/div[@class=&quot;p-t-15&quot;]/div[@class=&quot;bor8 bg0 m-b-12&quot;]/input[@class=&quot;stext-111 cl8 plh3 size-111 p-lr-15&quot;][count(. | //input[@class = 'stext-111 cl8 plh3 size-111 p-lr-15' and @type = 'text' and @name = 'address' and @placeholder = 'Address']) = count(//input[@class = 'stext-111 cl8 plh3 size-111 p-lr-15' and @type = 'text' and @name = 'address' and @placeholder = 'Address'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be4d5211-1394-43f5-aef9-7b44d9baaa12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stext-111 cl8 plh3 size-111 p-lr-15</value>
      <webElementGuid>753c4769-0eef-4570-aeee-110670c1a391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>def86980-8f1a-4ea5-9e51-facf4195a676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>590a32a1-7832-4a54-82e7-ae611ae917a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>45f58b13-3514-4e81-83c3-d265cdf46878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;animsition&quot;]/form[@class=&quot;bg0 p-t-75 p-b-85&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50&quot;]/div[@class=&quot;bor10 p-lr-40 p-t-30 p-b-40 m-l-63  m-lr-0-xl p-lr-15-sm&quot;]/div[@class=&quot;flex-w flex-t bor12 p-t-15 p-b-30&quot;]/div[@class=&quot;size-209 p-r-18 p-r-0-sm w-full-ssm&quot;]/div[@class=&quot;p-t-15&quot;]/div[@class=&quot;bor8 bg0 m-b-12&quot;]/input[@class=&quot;stext-111 cl8 plh3 size-111 p-lr-15&quot;]</value>
      <webElementGuid>11338e0f-9350-44d9-b7c9-8edac439bed0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='address']</value>
      <webElementGuid>e1dc2a72-f6c2-41a8-a876-dedfc0b2ce4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>72e1238a-e29c-43fc-9da5-11f7489a06f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address' and @placeholder = 'Address']</value>
      <webElementGuid>b6942372-50cc-4df0-a6bc-00a9b08f5977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
