<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping_mobilenumber</name>
   <tag></tag>
   <elementGuidId>a52cc279-8275-497c-affc-e1d83f444c35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;mobilenumber&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;animsition&quot;]/form[@class=&quot;bg0 p-t-75 p-b-85&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50&quot;]/div[@class=&quot;bor10 p-lr-40 p-t-30 p-b-40 m-l-63  m-lr-0-xl p-lr-15-sm&quot;]/div[@class=&quot;flex-w flex-t bor12 p-t-15 p-b-30&quot;]/div[@class=&quot;size-209 p-r-18 p-r-0-sm w-full-ssm&quot;]/div[@class=&quot;p-t-15&quot;]/div[@class=&quot;bor8 bg0 m-b-12&quot;]/input[@class=&quot;stext-111 cl8 plh3 size-111 p-lr-15&quot;][count(. | //input[@class = 'stext-111 cl8 plh3 size-111 p-lr-15' and @type = 'text' and @name = 'mobilenumber' and @placeholder = 'Mobile number']) = count(//input[@class = 'stext-111 cl8 plh3 size-111 p-lr-15' and @type = 'text' and @name = 'mobilenumber' and @placeholder = 'Mobile number'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='mobilenumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61063baf-0d8a-4193-ad55-79762f166ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stext-111 cl8 plh3 size-111 p-lr-15</value>
      <webElementGuid>0e09219c-323e-40e1-aa14-d5a2a2a66dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c298c3c-babd-4b92-9d7d-99093f590f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobilenumber</value>
      <webElementGuid>a3da57eb-fd9d-4a7b-acf4-1dd8d5b53d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile number</value>
      <webElementGuid>70e1b42a-6092-4599-927a-48d2408208b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;animsition&quot;]/form[@class=&quot;bg0 p-t-75 p-b-85&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50&quot;]/div[@class=&quot;bor10 p-lr-40 p-t-30 p-b-40 m-l-63  m-lr-0-xl p-lr-15-sm&quot;]/div[@class=&quot;flex-w flex-t bor12 p-t-15 p-b-30&quot;]/div[@class=&quot;size-209 p-r-18 p-r-0-sm w-full-ssm&quot;]/div[@class=&quot;p-t-15&quot;]/div[@class=&quot;bor8 bg0 m-b-12&quot;]/input[@class=&quot;stext-111 cl8 plh3 size-111 p-lr-15&quot;]</value>
      <webElementGuid>3d550f13-69ab-44c4-9aa9-058724f0b98e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='mobilenumber']</value>
      <webElementGuid>9109ebd4-a7fc-4f7d-b822-f2e8a8704c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2cb8d498-8e85-4a28-a943-b6007cc25d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mobilenumber' and @placeholder = 'Mobile number']</value>
      <webElementGuid>b84e6840-79ac-4147-a712-cf668985acfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
