<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quantity_productNumber</name>
   <tag></tag>
   <elementGuidId>3c5c0de1-64ca-4165-8f81-6e01eebbe4ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='productQuantity']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;productQuantity&quot;)[count(. | //input[@class = 'mtext-104 cl3 txt-center num-product' and @type = 'number' and @name = 'productNumber' and @id = 'productQuantity' and @value = '1']) = count(//input[@class = 'mtext-104 cl3 txt-center num-product' and @type = 'number' and @name = 'productNumber' and @id = 'productQuantity' and @value = '1'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productQuantity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>144c2fa4-117d-4f08-b1e2-b38774ff9f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mtext-104 cl3 txt-center num-product</value>
      <webElementGuid>9192a25f-b49d-47fc-b37e-b7e5a3fee5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6aa82025-cd03-4783-b0a4-5285e6aab9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>productNumber</value>
      <webElementGuid>f29c8b2b-a6e7-47aa-a9e5-12fcc9c38c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productQuantity</value>
      <webElementGuid>d13f0f69-9385-4620-ac91-be8e8edb4f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bc43f252-ebbc-4154-89e4-7bd8297fb0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productQuantity&quot;)</value>
      <webElementGuid>3223cd02-d9d8-48be-aa6b-d5f3771b3f08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='productQuantity']</value>
      <webElementGuid>860aa31d-b34a-4375-baf5-0ad1c93602d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>afbcf95e-a25d-46cc-9649-2386a8fe4a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'productNumber' and @id = 'productQuantity']</value>
      <webElementGuid>7e16a8bf-ec13-475f-95c3-e1b055e5c102</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
