<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Logout</name>
   <tag></tag>
   <elementGuidId>22a38869-42c2-4358-a065-bae87fd6307c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.flex-c-m.trans-04.p-lr-25.form-in-a.active-top</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5558445d-bb2e-44bf-bfea-fc9b8295a670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6b369942-7be2-4507-96ad-74c4d8141ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-c-m trans-04 p-lr-25  form-in-a active-top</value>
      <webElementGuid>e9c109b4-4103-406b-90c4-0b0643604a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								Logout
							</value>
      <webElementGuid>409df464-2f2b-4e8a-b57d-17e934fbe740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;animsition&quot;]/header[1]/div[@class=&quot;container-menu-desktop&quot;]/div[@class=&quot;top-bar&quot;]/div[@class=&quot;content-topbar flex-sb-m h-full container&quot;]/div[@class=&quot;right-top-bar flex-w h-full&quot;]/form[1]/button[@class=&quot;flex-c-m trans-04 p-lr-25  form-in-a active-top&quot;]</value>
      <webElementGuid>328efa9d-7689-4154-b957-3f7ea7a737c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>130b66ca-916a-4e9a-8139-059a65826a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='katalon1'])[1]/preceding::button[1]</value>
      <webElementGuid>6bc101e6-27db-40b6-8784-36c9e8f41a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, Welcome to My Website'])[1]/preceding::button[1]</value>
      <webElementGuid>19e716fa-e772-45d4-805d-1dddaed66014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>2b059bc7-6890-4a2c-ae48-f96d946b5fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>5ca66dba-a45a-4c6c-80bf-d3fb9197ea8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
								Logout
							' or . = '
								Logout
							')]</value>
      <webElementGuid>2d7f7a5c-fc7a-467c-a33c-04d2a0573b7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
