<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Logout</name>
   <tag></tag>
   <elementGuidId>22a38869-42c2-4358-a065-bae87fd6307c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.flex-c-m.trans-04.p-lr-25.form-in-a.active-top</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;animsition&quot;]/header[1]/div[@class=&quot;container-menu-desktop&quot;]/div[@class=&quot;top-bar&quot;]/div[@class=&quot;content-topbar flex-sb-m h-full container&quot;]/div[@class=&quot;right-top-bar flex-w h-full&quot;]/form[1]/button[@class=&quot;flex-c-m trans-04 p-lr-25  form-in-a active-top&quot;][count(. | //button[@type = 'submit' and @class = 'flex-c-m trans-04 p-lr-25  form-in-a active-top' and (text() = '
								Logout
							' or . = '
								Logout
							')]) = count(//button[@type = 'submit' and @class = 'flex-c-m trans-04 p-lr-25  form-in-a active-top' and (text() = '
								Logout
							' or . = '
								Logout
							')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd63d646-950d-4985-930e-7e0d9e56de3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1bc60077-3cac-4518-b554-365570425ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-c-m trans-04 p-lr-25  form-in-a active-top</value>
      <webElementGuid>4996c9a3-c263-491e-be82-8a71be925879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								Logout
							</value>
      <webElementGuid>d2516226-3956-4a6d-a354-3cd444eaf5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;animsition&quot;]/header[1]/div[@class=&quot;container-menu-desktop&quot;]/div[@class=&quot;top-bar&quot;]/div[@class=&quot;content-topbar flex-sb-m h-full container&quot;]/div[@class=&quot;right-top-bar flex-w h-full&quot;]/form[1]/button[@class=&quot;flex-c-m trans-04 p-lr-25  form-in-a active-top&quot;]</value>
      <webElementGuid>3760ac2c-d27f-4e8e-96fc-0ba07ef1449a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>e1167c0a-3273-4b13-be6b-c6f08d0f9334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='katalon1'])[1]/preceding::button[1]</value>
      <webElementGuid>16038bf0-4fa2-45c7-8d44-678e7b1fc0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, Welcome to My Website'])[1]/preceding::button[1]</value>
      <webElementGuid>b65803e2-b866-467d-b891-b7fbca588dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>fb77ade1-7fb9-484b-a5df-004834d10912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>64299f9d-141a-4a77-a8e7-30ae11344c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
								Logout
							' or . = '
								Logout
							')]</value>
      <webElementGuid>43538ea9-9c09-4f4a-a139-360990ca2e9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
